### ISSUE TITLE
unit test failure in flightsql-dbapi

### ISSUE THREAD

**Issue by jdstrand** [influxdata/flightsql-dbapi#24]
https://github.com/influxdata/flightsql-dbapi/actions/runs/6501255996/job/17658240765?pr=23 show that unit tests failed when trying to apply https://github.com/influxdata/flightsql-dbapi/pull/23. These should be fixed for future maintenance.

**Comment by helenosheaa** [comment]
unit tests passing https://github.com/influxdata/flightsql-dbapi/pull/30
